### ISSUE TITLE
UI/UX enhancement

### ISSUE THREAD

**Issue by proffapt** [proffapt/fERP#10]
Improve the UI for the extension and make it appealing to eyes along with being descriptive:
- [x] Better interactive buttons 
- [x] Logo for the extension
- [x] Tooltip for the checkbox
- [x] Fix the size

**Comment by fiddyhamma** [comment]
Hello, I'd love to contribute to this project. Could you direct me to the extension?

**Comment by proffapt** [comment]
Have you enrolled in https://KWoC.kossjitkgp.org ?
This project is under it for next month.

**Comment by fiddyhamma** [comment]
Okay, not yet but I'll try to do so today. Thank you

**Comment by fiddyhamma** [comment]
I'm unable to access this link, it says to check for a correct spelling. Could you pls recheck the link you sent?

**Comment by proffapt** [comment]
> I'm unable to access this link, it says to check for a correct spelling. Could you pls recheck the link you sent?

ohh my bad, https://kwoc.kossiitkgp.org

**Comment by simrancs** [comment]
@proffapt Elaborate the 2nd point, didn't quite get that

**Comment by proffapt** [comment]
Completed by 2b0f68e
