### ISSUE TITLE
Update extension's LOGO 

### ISSUE THREAD

**Issue by proffapt** [proffapt/fERP#13]
- Currently the textures don't express out <img width="54" alt="image" src="https://user-images.githubusercontent.com/86282911/208615828-37aa3dc7-fa80-4f2a-8481-66759f9785e8.png">
  - [x] Make the rings a bit bigger
  - [x] Add a Dark mode compatible icon
  - [x] Add institutes logo somehow (Can google about IIT KGP easy to get.)

**Comment by simrancs** [comment]
Working on it! 💪🏻
