### ISSUE TITLE
Update Chrome extension to Manifest v3

### ISSUE THREAD

**Issue by proffapt** [proffapt/fERP#22]
Manifest v2 will not be supported in the near future, shifting to v3 will need to modify the codebase to huge extent.

Work is being done in #24

**Comment by harshkhandeparkar** [comment]
Meh switch to firefox

**Comment by harshkhandeparkar** [comment]
near future kaun dekhta hai

**Comment by proffapt** [comment]
@harshit-jain52 reply in this issue so that I can assign it to you

**Comment by harshit-jain52** [comment]
yes

**Comment by proffapt** [comment]
fixed in #26
