### ISSUE TITLE
not working properly on autocapta 

### ISSUE THREAD

**Issue by arpitkumar2004** [proffapt/fERP#42]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by proffapt** [comment]
Hi, I am aware. Currently occupied with placements. Will update once I get time.

**Comment by arpitkumar2004** [comment]
Ok, Best wishes for your Placement.

**Comment by proffapt** [comment]
Umm, it's actually working. It's not scalable, so it might fail when a lot of users use it. That's a different issue not in the scope of what I want to provide the users as.
