### ISSUE TITLE
Implement autofill captcha

### ISSUE THREAD

**Issue by proffapt** [proffapt/fERP#7]
#### Final step towards complete automation - Captcha solving automation

For now the user needs to fill captcha manually.

- Implementing this will need to change the code base to large extent, but will be easier as compared to current one.
- Utilising some API will be our first go-to method.

**Comment by sandptel** [comment]
I can solve the captcha on that website using opencv python and a ocr (pytesseract).

**Comment by proffapt** [comment]
Nice, try if you can!

**Comment by Vector-013** [comment]
Can this please be assigned to me as part of kwoc '23?

**Comment by jameel-azad** [comment]
Hi @proffapt I would like to solve this issue for kwoc'23. Can you please assign me this? Quick question, how are we going to test it since the feedback window is closed?

**Comment by proffapt** [comment]
let's discuss this on the slack channel. Ping me there.

**Comment by jameel-azad** [comment]
@proffapt can you please add me the ferp channel slack

**Comment by proffapt** [comment]
done
